import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const router = useRouter();

  // // 呼ぶとページがリロードされます。
  // router.reload()

  // // 呼ぶと前のページに戻れます
  // router.back()

  // // 遷移開始時のイベントを購読します
  // router.events.on("routerChangeStart",(url,{shallow}) =>{
  //   // url には遷移先のパスが与えられます
  //   // shallowにはシャロールーティング（パスのみが置き換わる遷移）の場合はtrue
  // })

  // // 線完了時のイベントを購読します
  // router.events.on("routerChangeComplete",(url,{shallow}) =>{
  //   // url には遷移先のパスが与えられます
  //   // shallowにはシャロールーティング（パスのみが置き換わる遷移）の場合はtrue
  // })


	const onSubmit = () => {
		// ssrへと遷移します
		router.push('/ssr');

		// 文字列の代わりにオブジェクトで指定できます
		// /ssg?keyword=heeloへ遷移します
		router.push({
			pathname: '/ssg',
			query: {
				keyword: 'hello',
			},
		});
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				{/* ssr へ遷移するためのリンクを作る */}
				<Link href='/ssr'>Go To SSR</Link>
				<Link href='/ssg?keword=next'>GO TO SSG</Link>
				{/* hrefに文字列を指定する代わりにオブジェクトを指定できます */}
				<Link
					href={{
						pathname: '/ssg',
						query: { keyword: 'hello' },
					}}>
					GO TO SSG
				</Link>
				<Link href='/ssg'>
					{/* aのかわりに button を使うと、 onClick が呼ばれたタイミングで遷移する */}
					<button>Jump to SSG Page</button>
				</Link>
			</main>
		</>
	);
}
